### ISSUE TITLE
Couldn't compile

### ISSUE THREAD

**Issue by hyubrad** [1runeberg/RunebergVRPlugin#1]
HI
i have a problem with this .After generated file with Visual Studio2015,and rebuild ,It apear this message "Could not be compiled. try rebuilding from source manually"

could you tell me how to fix this problem?

**Comment by 1runeberg** [comment]
Hi hyubrad - It may be you're using 4.12 (or something older than 4.11?), I havent had the chance to upload the upgraded version yet as I'm travelling and my main workstation is at home where I do my VR stuff.

Try right clicking on the uproject and upgrading it to 4.12, it should work without any issues.

Failing that, delete the Intermediate, Binary and Saved directories and double click the uproject file and say Yes to the error message that pops up for the dll rebuild.

Let me know if you still have any issues.

Cheers.

**Comment by jorgemarz** [comment]
Hi!

I get the same issue. I did the instructions you give, and yet, i get the following message:

Running C:/Program Files (x86)/Epic Games/4.12/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="C:/Users/VIRTUALRENDER/Desktop/UE4 TEMPLATES/RunebergVRPlugin-master/RunebergVR.uproject" -game -rocket -progress
Visual C++ 2015 toolchain does not appear to be correctly installed. Please verify that "Common Tools for Visual C++ 2015" was selected when installing Visual Studio 2015.
Discovering modules, targets and source code for project...
UnrealBuildTool Exception: ERROR: Visual Studio 2015 must be installed in order to build this target.

Can you help me with this issue? I really apreciate it!

Thanks

**Comment by 1runeberg** [comment]
Hi JorgeMarz - Do you have Visual Studio 2015 installed with the all the Visual C++ components?

If not I'll upload a binary (pre-compiled) version.

**Comment by jorgemarz** [comment]
No i don't :(

I'm an early stage enthusiast of the UE4, needless to say, my knowledge with this excellent software is nearly none u_u So, if you can upload a more simple HTC Vive template, i will thank you a lot! 

My intend is to build something like a room, with furniture and realistic lighting, so i can interact with.

Thanks!

**Comment by 1runeberg** [comment]
oh if u want to use the project as a vr template and also to learn with, it's best to install Visual Studio 2015 (Community edition is free) and select all the C++ modules in your PC during the install wizard. You don't need to use C++ or edit any code, UE just needs it to compile the plugin and the engine. 

You can use the plugin to interact with the furniture you import using the motion controllers (grab, push, pull) -- just add a "Physics Handle" component to them and make sure that "Physics enabled" is ticked in the static mesh/furniture you want to make "grabbable".

hopefully I get to post a couple more video tutorials next week, time permitting.

**Comment by jorgemarz** [comment]
Perfect! i Will

Thank you for your help :)
