### ISSUE TITLE
Throttle and Point Direction on Opposite Hands

### ISSUE THREAD

**Issue by ttrockiryba** [1runeberg/RunebergVRPlugin#7]
Hello, first of all thanks for the plugin! It's wonderful!! I was playing around with it and I can't seem to make it so that the throttle and the direction selection are on the same hand. Currently I throttle with the left and aim with the right, which is confusing and also makes it so I can't really use the right hand. 

Similarly, is there any way to make it so the movement speed/forward direction is dependent on the players finger position relative to the middle of the trackpad? (Trying to replicate the motion system from Onward, essentially.)

Thanks again!!

**Comment by 1runeberg** [comment]
Hi ttrockiryba! Thanks for the feedback. Doing some major refactoring this coming Easter holidays so will add these to the list.

For the movement direction via touch on the trackpad, you can use the node "Motion Controller (L)/(R) Thumbstick Y" and read its value (-1 to 1, 0 being the middle/no touch detected), you can then use the value from this node multiplied by some constant and plug that in for speed. You can enable movement as long as this value is not 0, disable otherwise. Does that help?

Cheers,
Rune.

**Comment by owenglobal** [comment]
hi, amazing plugin. thanks so much. how hard would it be for you to implement a iron man style thrusters system built into the hands/motion controllers. if it were reasonable accurate you could control your flight in very subtle ways like that. 
O

**Comment by 1runeberg** [comment]
@ttrockiryba - this has beein implemeted (Enable360Movement) a couple of versions back, so am now closing this issue :) Any questions, please jsut let me know.

@owenglobal - Thanks for the feedback! This should already be possible since v1 of the plugin :) Have a look at this tutorial:

https://www.youtube.com/watch?v=MfXD91JnPj0

You can use the trigger axis or any axis input to granularly  control speed if you need to. The Demo projec, VR Movement Map actually shows how this can be done. Hope that helps!
